### ISSUE TITLE
建议：代码和效果分开

### ISSUE THREAD

**Issue by yamsfeer** [Orillusion/orillusion-web#123]
文档中的代码示例，左边为效果，右边为对应代码
代码总是要左右滚动，非常不方便

**Comment by lslzl3000** [comment]
稍后会测试一版，默认全部显示demo，右下角按钮点击后再显示代码

**Comment by yamsfeer** [comment]
但是有个新问题，对于不支持webgpu的浏览器，代码按钮被更新浏览器的提示覆盖了

**Comment by yamsfeer** [comment]
我觉得上下分开或者用tab比较合适

**Comment by lslzl3000** [comment]
不支持webgpu的提示会覆盖按钮的问题修复了
上下分开有点太占篇幅了，而且大部分demo上下本身也有关键代码解释，再放上全部代码有点冗余
tab的形式在样式上有点复杂，没想好一个统一的style

我将这个 issue 保持 open 一段时间，再看看有没有其他一些好的建议

**Comment by lslzl3000** [comment]
暂时先保持目前的形式，有好的建议可以再打开
