### ISSUE TITLE
get english translation

### ISSUE THREAD

**Issue by tvortsa** [Orillusion/orillusion-web#175]
Hello!

If its possible to get english version of this reppo ? (i wish to do russian translate of it)

Thank you!

**Comment by lslzl3000** [comment]
You can see the english branch
https://github.com/Orillusion/orillusion-web/tree/en

basically it's synced with `main` branch zh docs
usually, we add latest new docs in `0.x` branches, currently it's `0.7`, will release `0.8` soon. After `0.8`, we will merge it to `main` branch, and than translate into `en` branch

**Comment by tvortsa** [comment]
Thank you very much!

Thank you for your job!
