### ISSUE TITLE
官网的 demo 报错了，最新的语法中 [[ 被 @ 替换了

### ISSUE THREAD

**Issue by XJawher** [Orillusion/orillusion-web#29]
查看了你们的官网demo，在 chrome 版本 101.0.4946.0（正式版本）canary （64 位） 中出错了

**Comment by SirXuNian** [comment]
- 在最新的浏览器中,取消 [[  改为 @; 
- loadValue 将改为 loadop 和 clearvalue;
- stencilValue  将改为 loadop 和 clearvalue;
- endPass 将改为 end;
以上是最新的Webgpu API的变化，暂时是警告，我们会在后续版本迭代上去

**Comment by lslzl3000** [comment]
为了兼顾低版本Chrome，暂时没有把wgsl语法升级到最新版，后续会迭代修复，或者根据Chrome版本自动适应wgsl的语法
