### ISSUE TITLE
Mac需要重启浏览器才能使用WEBGPU

### ISSUE THREAD

**Issue by indeexx** [Orillusion/orillusion-web#9]
Chrome版本： 97.0.4692.71（正式版本） (x86_64)
问题：刷新页面，访问Alpha Demo，报错：
umi.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'requestDevice')
    at umi.js:1:364887
需要重启浏览器后才能正常在navigator.gpu中找到设备。
多次刷新必显。

**Comment by lslzl3000** [comment]
当前webgpu标准还没有正式启用，浏览器默认是不支持的，需要开发者向 chrome 申请 origin-trail 测试权限，才可以在特定的域名页面启用 webgpu 的权限。
普通用户访问页面时会向chrome发送请求验证域名权限，验证通过才可以使用 webgpu 权限，该验证过程存在一定的不稳定因素，可能因为网络问题，或者google服务器延迟，造成一定机率验证失败。
对此，我们无法干预验证过程和结果，一旦验证失败，只能重启浏览器重新请求验证。
按目前chrome的开发计划，应该会在 102 版本中正式启用webgpu，在此之前，只能通过origin-trail 机制体验 webgpu，或者使用 chrome canary 版本强制打开 webgpu flag。
